name: Upload source files to Crowdin

on:
  push:
    branches: [ master ]
    paths:
      - 'romfs/lang/en/**'
  workflow_dispatch:

concurrency:
  group: crowdin-upload

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Push to Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
          UU_CROWDIN_ID: ${{ secrets.UU_CROWDIN_ID }}
